apiVersion: apps/v1
kind: Deployment
metadata:
  name: attachment-storage-service
  namespace: oih-dev-ns
  labels:
    app: attachment-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attachment-storage-service
  template:
    metadata:
      name: attachment-storage-service
      labels:
        app: attachment-storage-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: attachment-storage-service
        image: "openintegrationhub/attachment-storage-service:latest"
        envFrom:
        - configMapRef:
            name: attachment-storage-service
        env:
        - name: REDIS_CONFIG
          valueFrom:
            secretKeyRef:
              name: attachment-storage-service
              key: REDIS_CONFIG
        - name: IAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: attachment-storage-service
              key: IAM_TOKEN
        resources:
          limits:
            cpu: 0.1
            memory: 512Mi
        livenessProbe:
          httpGet:
            port: 3002
            path: /healthcheck
        readinessProbe:
          httpGet:
            port: 3002
            path: /healthcheck
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
